### ISSUE TITLE
[Research] - Maven plugins

### ISSUE THREAD

**Issue by rami-nk** [Miragon/miranum#111]
- [x] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description

For the refactoring task #92 it should be able to generate element templates on the build and not on startup like it is now. This task includes the research about how to create maven plugins. 

## Sub-Tasks
 
- [ ] How to create maven plugins?
- [ ] How can we adapt it to our problem?
- [ ] POV
