### ISSUE TITLE
[Feature] - CLI generate plain miranum workspace

### ISSUE THREAD

**Issue by rami-nk** [Miragon/miranum#112]
- [ ] Description created
- [ ] Reviewed by peer: @DaAnda97 
- [ ] Prioritised

# Description
The miranum workspace can be generated using the miranum cli.
The command can look like: mm new projectname --group com.example

## Sub-Tasks
 
- [ ]  Use miranum-cli as a basis
- [ ] Create maven project
- [ ] init git project
- [ ] Add stack with docker-compose.yaml
