### ISSUE TITLE
[Feature] - CLI generate service

### ISSUE THREAD

**Issue by rami-nk** [Miragon/miranum#113]
- [ ] Description created
- [ ] Reviewed by peer: @DaAnda97 
- [ ] Prioritised

# Description

Generate a service that contains a core with the hexagonal architecture.
Should be a submodule inside of a maven project.
Command can look like: mm gen <servicename>

## Sub-Tasks
 
- [ ] Generate mvn project as submodule
- [ ] Generate core as a submodule of the service module
- [ ] Add miranum dependencies
- [ ] Generate hexagonal architecture project structure
- [ ] Generate MVE (minimum viable example)
- [ ] Generate autoconfigs + spring.factories
