### ISSUE TITLE
[Feature] - CLI generate specific implementation project

### ISSUE THREAD

**Issue by rami-nk** [Miragon/miranum#114]
- [ ] Description created
- [ ] Reviewed by peer: @DaAnda97 
- [ ] Prioritised

# Description

Generate an implementation for a specified engine.
Command can look like this: mm impl c7

## Sub-Tasks
 
- [ ] Generate mvn submodule 
- [ ] Add spring boot deps
- [ ] Add miranum deps for specified engine
