### ISSUE TITLE
[Epic] - Refactor Miranum Platform

### ISSUE THREAD

**Issue by dominikhorn93** [Miragon/miranum#251]
- [ ] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description

We want to refactor the miranum-connect and miranum platform repository.

Things to care about:
- use miranum connect when interacting with the engine
  - there is no direct camunda dependency usage in the engine or task service (engine-neutral)
  - create adapter modules for engine/technologie dependencies

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] https://github.com/Miragon/miranum/issues/297
- [x] Remove pagination from process
- [ ] https://github.com/Miragon/miranum/issues/296
- [ ] https://github.com/Miragon/miranum/issues/289
- [ ] https://github.com/Miragon/miranum/issues/265
- [ ] https://github.com/Miragon/miranum/issues/294
- [ ] create e2e testing module
- [ ] add example for domain service
- [ ] create example tasklist frontend
- [x] introduce seperate versions for connect and platform
- [x] merge the connect and platform repo
- [ ] add jsonforms with minimalistic ui to the domain service example
- [ ] Implement a usertask example using json forms and json schema
- [ ] https://github.com/Miragon/miranum/issues/253
- [ ] https://github.com/Miragon/miranum/issues/255
- [ ] https://github.com/Miragon/miranum/issues/260
- [ ] https://github.com/Miragon/miranum/issues/263
- [ ] https://github.com/Miragon/miranum/issues/254
- [ ] https://github.com/Miragon/miranum/issues/291
- [ ] https://github.com/Miragon/miranum/issues/370
- [ ] https://github.com/Miragon/miranum/issues/371
- [ ] https://github.com/Miragon/miranum/issues/369
- [ ] https://github.com/Miragon/miranum/issues/368
- [ ] https://github.com/Miragon/miranum/issues/367
```

## Stakeholder
 

# Acceptance

**Comment by lmoesle** [comment]
@dominikhorn93 @DaAnda97 FYI I added the issues we have discussed to the epic
