### ISSUE TITLE
[Feature] Finalise Miranum Message

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum#62]
- [x] Description created
- [x] Reviewed by peer: @hauptmedia 
- [x] Prioritised

# Description
Finalise the needed functionality for Miranum Message. 
Therefore, we want to implement the CloudEvents infrastructure code & adapter for messages on Camunda 7 and Camunda 8 

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Implement CloudEvents infrastructure code
- [ ] Implement CloudEvents adapter 
- [ ] Test for Camunda 7 & 8 
- [ ] Update documentation 
```

**Comment by Hafflgav** [comment]
Hey @dominikhorn93, 
I am not sure what currently needs to be done to finalise Miranum Message. Can you fill out this feature with more detail? 
Thanks a lot in advance!

**Comment by hauptmedia** [comment]
this is related to what i'm working on right now: Implementing CloudEvents instructure code & adapter  for c7/c8, so you can assign it to me, i will work on it until i can verify that we have a working solution here

**Comment by Hafflgav** [comment]
Thanks for the update @hauptmedia. I just assigned you and will update + move this issue to "in progress". 💯
