### ISSUE TITLE
[Epic] - Add Miranum Connect support for Flowable

### ISSUE THREAD

**Issue by rami-nk** [Miragon/miranum#67]
- [x] Description created
- [x] Reviewed by peer: @Hafflgav 
- [x] Prioritised

# Description
As a user of Flowable I want to be able to create integrations for my processes using Miranum Connect. I want to be able to use all features Miranum Connect currently offers for Camunda 7 and Camunda 8 Platform, such as worker registration, process start and message correlation.

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] https://github.com/FlowSquad/miranum/issues/71
- [ ] https://github.com/FlowSquad/miranum/issues/68
- [ ] https://github.com/FlowSquad/miranum/issues/69
- [ ] https://github.com/FlowSquad/miranum/issues/70
- [ ] https://github.com/FlowSquad/miranum/issues/71
```

## Stakeholder
@Hafflgav @dominikhorn93 

# Acceptance
- A worker use case implementation for Flowable
- A process use case implementation for Flowable
- A message correlation use case implementation for Flowable 
- I can create any workflow that is currently supported for Camunda7/8 Platform using Flowable.
- The current examples which are implemented for C7/8 are extended to have Flowable example

**Comment by Hafflgav** [comment]
Hey @rami-nk & @dominikhorn93, 
given that we had some problems leveraging the external task pattern in Flowable, I have had a chat with one of their solution consultants. His recommendation was to rather publish events to a message queue and consume them from there. This is how they communicate with microservices in their projects most of the time. 

Wdyt?

**Comment by dominikhorn93** [comment]
If that is the case, how is error & Incident handling done?
What about retries?
Are they using send reply pattern with message correlation?

We do the same at LHM by providing a "streaming template" that is used by every integration.
At this point the element templates change and things get a bit more complicated.
@lmoesle our pair programming 1 month ago in combination with a BPMN Call Activity should be a good start I guess?
