### ISSUE TITLE
[Feature] - Flowable worker use case implementation

### ISSUE THREAD

**Issue by rami-nk** [Miragon/miranum#68]
- [x] Description created
- [x] Reviewed by peer: @Hafflgav 
- [x] Prioritised

# Description
As a user of Flowable as a workflow-engine I want to be able to register an external Task (Worker) inside of Miranum

## Sub-Tasks
- [ ] Create flowable-worker-adapter and implement BindWorkerPort
- [ ] Expose adapter as bean with autoconfiguration
- [ ] Support throw BPMN error in service task
- [ ] Extend docs and tests
- [ ] Extend simple example with flowable implementation

**Comment by Hafflgav** [comment]
Hey @rami-nk, 
small comment - I would add this subtask to here as well:
* Support throw BPMN error event in service task

Wdyt?
