### ISSUE TITLE
[Feature] - Flowable process use case implementation

### ISSUE THREAD

**Issue by rami-nk** [Miragon/miranum#69]
- [x] Description created
- [x] Reviewed by peer: @Hafflgav 
- [x] Prioritised

# Description
As a user of Flowable as a workflow-engine I want to be able to start a process through miranum.

## Sub-Tasks
- [ ] Create flowable-process-adapter and implement StartProcessPort
- [ ] Expose adapter as bean with autoconfiguration
- [ ] Extend docs and tests
- [ ] Extend start process example
