### ISSUE TITLE
Create deployment and write instructions for miranum/digiwf

### ISSUE THREAD

**Issue by dominikhorn93** [Miragon/miranum#7]
## Description
Write a description and instruction for deploying miranum/digiwf in kubernetes

### Tasks

- [ ] Create a description for deploying KeyCloak if no auth2 setup is provided 
- [ ] Deploy Digiwf-Engine
- [ ] Deploy Digiwf-Tasklist
- [ ] Deploy LDAP
- [ ] Deploy Miranum Deployment Proxy
- [ ] Deploy S3 Service and connect it to google cloud storage 

### Criteria

- [ ] It is possible to model and deploy bpmn and form artifacts via IDE
- [ ] It is possible to login and start the above modeled process
- [ ] It is possible to login into camunda cockpit as camunda-admin user
- [ ] It is possible to login into digiwf task list via demo user (john doe)

### HInts
- use digiwf-ops repo as starting point
- digiwf-engine, digiwf-tasklist, digiwf-document-storage (should have a public image), digiwf-gateway
