### ISSUE TITLE
[Feature] - Flowable message correlation use case implementation

### ISSUE THREAD

**Issue by rami-nk** [Miragon/miranum#70]
- [x] Description created
- [x] Reviewed by peer: @Hafflgav 
- [x] Prioritised

# Description

As a user of Flowable as a workflow-engine I want to be able to correlate messages inside a miranum worker. 

## Sub-Tasks
 
- [ ] Create flowable-message-adapter and implement DeliverMessagePort
- [ ] Expose adapter as bean with autoconfiguration
- [ ] Extend docs and tests
- [ ] Extend simple example with a flowable implementation
