### ISSUE TITLE
[Feature] - Extend missing examples with a Flowable implementation

### ISSUE THREAD

**Issue by rami-nk** [Miragon/miranum#72]
- [x] Description created
- [x] Reviewed by peer: @Hafflgav 
- [x] Prioritised

# Description
After Miranum Connect supports Flowable a user should be able to view the currently available examples and see how he can use Miranum Connect with Flowable. Some examples are already extended with a Flowable implementation. 

## Sub-Tasks
- [ ] Look for examples that do not contain Flowable implementation
- [ ] Add Flowable implementation
- [ ] Extend docs
