### ISSUE TITLE
[Feature] - More intuitive package structure for process artefacts 

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum#90]
- [x] Description created
- [ ] Reviewed by peer: @dominikhorn93 
- [ ] Prioritised

# Description
We want to establish a more meaningful package structure when it comes to handling process artefacts. Currently, Miranum CLI creates a package structure which does not really fit into a Miranum connect project. Element templates are not being taken into account as well. 

We want to have the artefacts structured in an intuitive way and ideally in one place so we can release them as an npm package easily. 

E.g.: 
showroom
 - service A
 - service B
 - modeling
    - bpmn
        - C7 
        - C8
    - forms
    - Element Templates 
        - C7 
        - C8

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Brainstorm proper folder structure 
- [ ] Update Miranum CLI 
- [ ] Update Element Template Generation
```
