### ISSUE TITLE
[Feature] - Package Manager for process artefacts

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum#91]
- [x] Description created
- [ ] Reviewed by peer: @dominikhorn93 
- [ ] Prioritised

# Description
To serve versioned element-templates, `bpmn` files and forms to other teams and departments in automation projects we need some kind of package manager. Ideally we can use npm and add a `package.json` to our process artefact directory. 

Furthermore, there should be a catalogue of processes, element-templates and forms which should be searchable. (Could be a GitHub repo or similar.) 

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Try releasing artefacts using npm 
- [ ] Build an exemplary catalogue which shows the artefacts in a searchable way. 
```
